// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0AgcaZKk3j2x1Lwraoffut1HLXVG4y98',
    appId: '1:440607721662:web:4909e2dc3789094992f6ef',
    messagingSenderId: '440607721662',
    projectId: 'khalasha-53a85',
    authDomain: 'khalasha-53a85.firebaseapp.com',
    storageBucket: 'khalasha-53a85.appspot.com',
    measurementId: 'G-K6F6HLSQ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz94HV6LXsSw3rdMSMnGFKvKJ82ZgiNmk',
    appId: '1:440607721662:android:5d2930441d9a480592f6ef',
    messagingSenderId: '440607721662',
    projectId: 'khalasha-53a85',
    storageBucket: 'khalasha-53a85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGoECGoLFjC7HAPnZRlfhh6dNXKuI_OK0',
    appId: '1:440607721662:ios:5c19e8640cfe264192f6ef',
    messagingSenderId: '440607721662',
    projectId: 'khalasha-53a85',
    storageBucket: 'khalasha-53a85.appspot.com',
    iosClientId: '440607721662-imkbrst638is9msabl88sbpsega9irik.apps.googleusercontent.com',
    iosBundleId: 'com.app.khalsha',
  );
}
