// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGBlDWegvh-P_I2UJEIChRgbxJgVc-Qhg',
    appId: '1:949672352683:web:90d2d5f3202486f17cd0ee',
    messagingSenderId: '949672352683',
    projectId: 'khalsha-54b3c',
    authDomain: 'khalsha-54b3c.firebaseapp.com',
    storageBucket: 'khalsha-54b3c.appspot.com',
    measurementId: 'G-KPE7MN7QNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQC2FPMiLYHKtzkQjdyp3S3hjUTbrJ0u8',
    appId: '1:949672352683:android:0afaeb6bfa0ae9d57cd0ee',
    messagingSenderId: '949672352683',
    projectId: 'khalsha-54b3c',
    storageBucket: 'khalsha-54b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWtSyt_mIhXdAGdHledoj72w_jfC0WJ0',
    appId: '1:949672352683:ios:840f26de7a1c8bdc7cd0ee',
    messagingSenderId: '949672352683',
    projectId: 'khalsha-54b3c',
    storageBucket: 'khalsha-54b3c.appspot.com',
    iosClientId:
        '949672352683-2kmd8rpqcivrrskkd20vukhhur0q6i3r.apps.googleusercontent.com',
    iosBundleId: 'com.app.khalsha',
  );
}
